log_format soc_json escape=json '{ 
  "time":"$time_iso8601",
  "ip":"$remote_addr",
  "method":"$request_method",
  "uri":"$request_uri",
  "status":$status,
  "ua":"$http_user_agent"
}';

access_log /var/log/nginx/soc_access.log soc_json;
